// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83aT-cPePTFJozfzEG50ZiZYfzF3lIjU',
    appId: '1:227382904545:web:34a19cac1c112b755219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    authDomain: 'devhabit-4517.firebaseapp.com',
    storageBucket: 'devhabit-4517.appspot.com',
    measurementId: 'G-NDJVZEJ8NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAF67wQNozh1_C4UkTO5hUTUBCWYls5KM',
    appId: '1:227382904545:android:27acdc72c260f3345219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfiWpgzIz-pvB6Qf59rxHX-gkmvc6BUo',
    appId: '1:227382904545:ios:bb96cadbc142d0735219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
    iosClientId: '227382904545-qqratkfopgkk2c4hcoohvs78v6u32sea.apps.googleusercontent.com',
    iosBundleId: 'com.example.devhabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfiWpgzIz-pvB6Qf59rxHX-gkmvc6BUo',
    appId: '1:227382904545:ios:233002b9601c3b815219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
    iosClientId: '227382904545-b26f1b2ciub41s1prtv0mah65nq6jjoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.devhabit.RunnerTests',
  );
}
