// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83aT-cPePTFJozfzEG50ZiZYfzF3lIjU',
    appId: '1:227382904545:web:34a19cac1c112b755219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    authDomain: 'devhabit-4517.firebaseapp.com',
    storageBucket: 'devhabit-4517.appspot.com',
    measurementId: 'G-NDJVZEJ8NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAF67wQNozh1_C4UkTO5hUTUBCWYls5KM',
    appId: '1:227382904545:android:b93b67eaec7bcfdf5219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfiWpgzIz-pvB6Qf59rxHX-gkmvc6BUo',
    appId: '1:227382904545:ios:027492f3b6fd41cc5219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
    androidClientId: '227382904545-02lqfq3oeg7rusqhnjbqabs88lflnlcv.apps.googleusercontent.com',
    iosClientId: '227382904545-9en3o7q26epgp0r5ojad9djehcsiukqs.apps.googleusercontent.com',
    iosBundleId: 'com.opxica.devhabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfiWpgzIz-pvB6Qf59rxHX-gkmvc6BUo',
    appId: '1:227382904545:ios:8d2fa7c9e2e93b5a5219a0',
    messagingSenderId: '227382904545',
    projectId: 'devhabit-4517',
    storageBucket: 'devhabit-4517.appspot.com',
    androidClientId: '227382904545-02lqfq3oeg7rusqhnjbqabs88lflnlcv.apps.googleusercontent.com',
    iosClientId: '227382904545-3cl7umpom8dg52aenu0ab734n2fa4idc.apps.googleusercontent.com',
    iosBundleId: 'com.opxica.devhabit.RunnerTests',
  );
}
